### ISSUE TITLE
Path is: /control spam

### ISSUE THREAD

**Issue by iamtpage** [hpeyerl/venstar_colortouch#11]
Hi,

I use this component as an integration in my home assistant instance, and I notice that the message above is spammed in the console quite frequently with no way to turn it off:

https://github.com/hpeyerl/venstar_colortouch/blob/c3b8aff9f7fce59f566685967363d429e2341c6c/src/venstarcolortouch/venstarcolortouch.py#L222

Would it be possible to put this message behind some sort of debug/logging option instead of printing it everytime?

**Comment by hpeyerl** [comment]
Yeah, you're right.  I deleted some debug crap in the 0.8 release I just did but should have gone a bit further.  I'll push a 0.9.
