### ISSUE TITLE
Possibly some extraneous debug statements?

### ISSUE THREAD

**Issue by iamtpage** [hpeyerl/venstar_colortouch#12]
https://github.com/hpeyerl/venstar_colortouch/blob/dc4f3c0a41c2850e9a67ee30b063c07c2ed478a8/src/venstarcolortouch/venstarcolortouch.py#L228

Would it be possible to remove this print statement? So if the function succeeds we don't see anything, but if it fails we see the error message listed here:

https://github.com/hpeyerl/venstar_colortouch/blob/dc4f3c0a41c2850e9a67ee30b063c07c2ed478a8/src/venstarcolortouch/venstarcolortouch.py#L231

Otherwise everytime you run a command, it starts filling up the log with success messages:
```
2019-09-06 18:02:00 INFO (MainThread) [homeassistant.setup] Setting up logger
Config directory: /config
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
set_control Success!
```

**Comment by hpeyerl** [comment]
Sorry for the delay.  Not ignoring you; just busy.

Seems reasonable; if you submit a merge request I'll approve it.  Otherwise I can try to do something with it this weekend.

**Comment by iamtpage** [comment]
I'll work on this today or tomorrow.

Thank you,

Tyler Page

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
