### ISSUE TITLE
backwords compatibility

### ISSUE THREAD

**Issue by alekseyn1** [hpeyerl/venstar_colortouch#14]
Hello,

I am trying to 'dumb' this down to work with T6800 that does not have an 'away' mode. I am not sure that this is the exact issue I am having, but base on the error - this is my issue. 

I will add the adjusted file to custom_components.

If you have a chance, I would appreciate any assistance. The description is here - https://community.home-assistant.io/t/venstar-t6800-thermostat-not-seen-by-ha/137010

Thank you in advance.

**Comment by hpeyerl** [comment]
If you can come up with a way to abstract away the Home/Away support for T6800 without affecting the others, and submit a merge request, I'll put it in.  Unfortunately, I have no control over the HomeAssistant component.
