### ISSUE TITLE
No support for remote interior sensors

### ISSUE THREAD

**Issue by garbled1** [hpeyerl/venstar_colortouch#21]
This is a bit more complex, so if I get to it, might be a few weeks.

My device has a remote sensor. My remote sensor is set as an alternate interior sensor.  This makes things extra fun apparently:

```
{"name":"Cave","mode":3,"state":0,"fan":0,"fanstate":0,
"tempunits":0,"schedule":0,"schedulepart":255,"away":0,
"spacetemp":77.0,"heattemp":72.0,"cooltemp":79.0,
"cooltempmin":35.0,"cooltempmax":99.0,"heattempmin":35.00,
"heattempmax":99.0,"activestage":0,"hum_active":0,"hum":50,
"hum_setpoint":0,"dehum_setpoint":99,"setpointdelta":2.0,"availablemodes":0}

{"sensors":[{"name":"Thermostat","temp":77.0,"hum":50},
{"name":"Space Temp","temp":77.0},
{"name":"Remote","temp":76.0}]}
```

I'm leaving this here for a bit in case anyone wants to tackle, otherwise I might take a crack at it.. it would involve some refactoring...  (Space temp is an average of Thermostat and Remote)

**Comment by hpeyerl** [comment]
There was an indentation error that appeared with one of the other merges when I tried to compile a package this morning.  I haven't been able to test your changes plus the previous merge.  So I'm somewhat loathe to push a 0.11 release.  Are you able to do a pull and test 'master'?
