### ISSUE TITLE
Code fails on Venstar T4800 and T4900 Commercial Thermostats

### ISSUE THREAD

**Issue by broswell** [hpeyerl/venstar_colortouch#23]
My Fixes

172,173c172
<         if self._type != "commercial":  #Commercial thermostats don't support "away"
<           self.away = self.get_info("away")
---
>         self.away = self.get_info("away")
198,199c197
<         #elif self.model == "COLORTOUCH":
<         elif self.model == "VYG-4900-VEN" or self.model == "VYG-4800-VEN" or self.model == "COLORTOUCH":
---
>         elif self.model == "COLORTOUCH":

**Comment by hpeyerl** [comment]
I'm more likely to be able to handle this in a timely manner if you send a pull request.   Thanks!

**Comment by broswell** [comment]
Never done one before.  Will learn how!

Bob Roswell
broswell@syssrc.com
410-771-5544 ext 4336

Computer Museum Highlights<http://museum.syssrc.com/>

[syssrclogo_38years]

From: Herb Peyerl
Sent: Friday, February 14, 2020 11:12 AM
To: hpeyerl/venstar_colortouch <venstar_colortouch@noreply.github.com>
Cc: Bob Roswell <broswell@syssrc.com>; Author <author@noreply.github.com>
Subject: [EXTERNAL] Re: [hpeyerl/venstar_colortouch] Code fails on Venstar T4800 and T4900 Commercial Thermostats (#23)


I'm more likely to be able to handle this in a timely manner if you send a pull request. Thanks!

**Comment by broswell** [comment]
Hope I did the pull request properly. Sorry, Github newbie.

Bob Roswell
broswell@syssrc.com
410-771-5544 ext 4336

Computer Museum Highlights<http://museum.syssrc.com/>

[syssrclogo_38years]

From: Herb Peyerl
Sent: Friday, February 14, 2020 11:12 AM
To: hpeyerl/venstar_colortouch <venstar_colortouch@noreply.github.com>
Cc: Bob Roswell <broswell@syssrc.com>; Author <author@noreply.github.com>
Subject: [EXTERNAL] Re: [hpeyerl/venstar_colortouch] Code fails on Venstar T4800 and T4900 Commercial Thermostats (#23)


I'm more likely to be able to handle this in a timely manner if you send a pull request. Thanks!
