### ISSUE TITLE
Typo in repository URL / pypi homepage

### ISSUE THREAD

**Issue by tv42** [hpeyerl/venstar_colortouch#26]
https://github.com/hpeyerl/venstar_colortouch/blob/175042b091b814c8e118780c032f1e9ebbc2426c/src/venstarcolortouch/__init__.py#L5

is missing the underscore. This makes the homepage link on https://pypi.org/project/venstarcolortouch/ wrong.

**Comment by hpeyerl** [comment]
Thanks.  Fixed in 0.14.
