### ISSUE TITLE
Schedule is always turned on when away mode is turned off

### ISSUE THREAD

**Issue by stbenjam** [hpeyerl/venstar_colortouch#9]
First: thank you for writing this, it works great!  With the recent Nest announcements, I ditched it and bought a thermostat with local control.  Everything works great now that I updated to 0.7, however I don't make use of the schedule functionality.

9194fa3e0d510ff05d88823eb41571e01e2990d7 introduced the behavior that turning away off, the schedule always gets turned on.  The comments say that you can't set away mode to 'on' when a schedule is also set, but this doesn't seem to be the case on my Venstar. See curl output below, and information about my API version.

Is this fixed in my firmware's API version? Or did you encounter this behavior on a different thermostat? I have a T7850.

I'm happy to open a PR but not sure what the best way to fix it is. Thoughts?

- Could we rely on the end user of this library to call set_schedule themselves before/after caling set_away?  This would be my preference, by having the user of the library overcome the quirk in whatever firmware does this, rather than assuming all users want schedules turned on.

- Could we only do this behavior on affected Thermostat firmwares?

```json
{
    "api_ver": 7, 
    "type": "residential",
    "model": "COLORTOUCH",
    "firmware": "5.10"
}
```

Schedule is on, away is off:

```console
$ curl -s http://thermostat.home.bitbin.de/query/info | jq '{schedule: .schedule, away: .away}'
{
  "schedule": 1, 
  "away": 0
}
$ curl -d "away=1" -X POST http://thermostat.home.bitbin.de/settings
{"success":true}
$ curl -s http://thermostat.home.bitbin.de/query/info | jq '{schedule: .schedule, away: .away}'
{
  "schedule": 1, 
  "away": 1
}

```

**Comment by hpeyerl** [comment]
I was able to confirm that my unit operates the same as yours when I use the curl commands.  I need to try it in HomeAssistant to see if I can reproduce what I was seeing back in October that caused me to make those changes in the first place.  I can only do it when I'm out at the place with the thermostat though.  I'll get back to you when I've had a chance.

**Comment by nkaminski** [comment]
This was addressed in PR #10

**Comment by stbenjam** [comment]
Thanks

**Comment by nkaminski** [comment]
@stbenjam I'm assuming that if you are hitting this issue, you are likely using this lib with Home Assistant. If so, build this as 0.8 and apply the following patch to the Venstar component to make  preset_mode/hold_mode fully functional: https://github.com/nkaminski/home-assistant/tree/venstar-0.8pre

**Comment by stbenjam** [comment]
I have a patch locally already that works but it would be good to get an official update in Home Assistant 0.97.

@hpeyerl would you mind releasing 0.8 to PyPi when you have a chance?

**Comment by hpeyerl** [comment]
I can release a 0.8 anytime.  I have to think about what this is going to do to my HomeAssistant.  I want it to go on-schedule when I turn off 'Away'.
